### ISSUE TITLE
Risk introducing nonce reuse

### ISSUE THREAD

**Issue by tbrezot** [Cosmian/kms#64]
In the Redis + Findex storage back-end, in [`object_upsert`](https://github.com/Cosmian/kms/blob/548ca190ba74664e33aaf51c6d8c6209f1968a32/crate/server/src/database/redis/objects_db.rs#L131), the Redis value is [encrypted](https://github.com/Cosmian/kms/blob/548ca190ba74664e33aaf51c6d8c6209f1968a32/crate/server/src/database/redis/objects_db.rs#L112) using a KDF256 of the Redis UID as nonce. This will cause a nonce reuse if the Redis table is mutated. Such mutation is allowed through the function [`update_object`](https://github.com/Cosmian/kms/blob/548ca190ba74664e33aaf51c6d8c6209f1968a32/crate/server/src/database/redis/redis_with_findex.rs#L315). Therefore, keys modified using this function should be considered as leaked.

You can use the UID as associated data in order to cryptographically link UIDs with their values. I don't think there is a way to avoid storing the nonce without making the whole DB immutable.

**Comment by bgrieder** [comment]
Although object updates are unlikely, they may happen, and we should improve this.
Let us use a random Nonce that is stored with an object. I would also suggest keeping the uid as part of the stored content (since the DEM is authenticated) as we want to prevent an attack where values are switched between 2 Uids

**Comment by bgrieder** [comment]
PR #65 created against main for quick release; single commit to be cherry-picked on develop.

Note: this is a breaking change on the ciphertexts, but since we just introduced FindexRedis and it is meant to be run in (future) TEEs, I do not think it is an issue. It it is, it will be easy to introduce a fallback on the previous decryption mechanism if the old one fails
